"""StabilityMap class for generating stability maps for given elements and phases.

This class uses the pycalphad library to calculate the eigenvalues of the Hessian of the Gibbs
energy with respect to the chemical potentials of the components, across a range of compositions,
and plots the results. The resulting map identifies regions of stability and phase separation in
a multi-component system.
"""

from __future__ import annotations

import itertools
import os
import warnings
from concurrent.futures import ProcessPoolExecutor
from typing import TYPE_CHECKING

import numpy as np
import pandas as pd
from pymatgen.core import Composition
from scipy.constants import Avogadro

from materialsframework.analysis.elastic_constants import ElasticConstantsAnalyzer
from materialsframework.tools.sqsgen import SqsGenerator
from materialsframework.utils import default_calculator, lazy_property, requires

if TYPE_CHECKING:
    from pycalphad import Database
    from pymatgen.core import Structure

    from materialsframework.tools.calculator import BaseCalculator

warnings.filterwarnings("ignore")

__authors__ = ["Doguhan Sariturk", "Courtney Kunselman"]
__maintainer__ = "Doguhan Sariturk"
__email__ = "dogu.sariturk@gmail.com"


class StabilityMap:
    """Class to generate a stability map for a given set of elements and phase.

    Attributes:
        dbf (Database): The thermodynamic database.
        elements (list): List of elements to include in the stability map.
        phase (str): The phase to include in the stability map.
        compositions (pd.DataFrame): DataFrame containing all valid compositions.
        temperature (float): Temperature in Kelvin.
        pressure (float): Pressure in Pascals.

    Methods:
        fit(): Fit the stability map by calculating eigenvalues and determining sections.
        plot(): Plot the stability map.

    Notes:
        The stability map is generated by calculating the eigenvalues of the Hessian
        of the Gibbs energy with respect to the chemical potentials of the components.
    """

    ORTHOGONALIZATION = np.array(
        [
            [
                -1,
                -1 / np.sqrt(3),
                -1 / np.sqrt(6),
                -1 / np.sqrt(10),
                -1 / np.sqrt(15),
                -1 / np.sqrt(21),
                -1 / (2 * np.sqrt(7)),
                -1 / 6,
                -1 / (3 * np.sqrt(5)),
            ],
            [
                1,
                -1 / np.sqrt(3),
                -1 / np.sqrt(6),
                -1 / np.sqrt(10),
                -1 / np.sqrt(15),
                -1 / np.sqrt(21),
                -1 / (2 * np.sqrt(7)),
                -1 / 6,
                -1 / (3 * np.sqrt(5)),
            ],
            [
                0,
                2 / np.sqrt(3),
                -1 / np.sqrt(6),
                -1 / np.sqrt(10),
                -1 / np.sqrt(15),
                -1 / np.sqrt(21),
                -1 / (2 * np.sqrt(7)),
                -1 / 6,
                -1 / (3 * np.sqrt(5)),
            ],
            [
                0,
                0,
                np.sqrt(3) / np.sqrt(2),
                -1 / np.sqrt(10),
                -1 / np.sqrt(15),
                -1 / np.sqrt(21),
                -1 / (2 * np.sqrt(7)),
                -1 / 6,
                -1 / (3 * np.sqrt(5)),
            ],
            [
                0,
                0,
                0,
                2 * np.sqrt(2) / np.sqrt(5),
                -1 / np.sqrt(15),
                -1 / np.sqrt(21),
                -1 / (2 * np.sqrt(7)),
                -1 / 6,
                -1 / (3 * np.sqrt(5)),
            ],
            [
                0,
                0,
                0,
                0,
                np.sqrt(5) / np.sqrt(3),
                -1 / np.sqrt(21),
                -1 / (2 * np.sqrt(7)),
                -1 / 6,
                -1 / (3 * np.sqrt(5)),
            ],
            [
                0,
                0,
                0,
                0,
                0,
                2 * np.sqrt(3) / np.sqrt(7),
                -1 / (2 * np.sqrt(7)),
                -1 / 6,
                -1 / (3 * np.sqrt(5)),
            ],
            [0, 0, 0, 0, 0, 0, np.sqrt(7) / 2, -1 / 6, -1 / (3 * np.sqrt(5))],
            [0, 0, 0, 0, 0, 0, 0, 4 / 3, -1 / (3 * np.sqrt(5))],
        ]
    )

    @requires("pycalphad", extra="calphad")
    def __init__(
        self,
        db: Database | str,
        elements: list[str] | None = None,
        phase: str | None = None,
        step: float = 0.05,
        temperature: int | float = 1500,
        pressure: int | float = 101325,
        nb_workers: int | None = None,
    ) -> None:
        """Initialize the StabilityMap class.

        Args:
            db (Database | str): pycalphad Database object or path to the thermodynamic database file.
            elements (list[str] | None, optional): List of elements to include in the stability map.
                If not provided, all elements in the database will be used.
            phase (str | None, optional): The phase to include in the stability map.
                If not provided, the phase in the database will be used.
            step (float, optional): Step size for generating compositions. Default is 0.05, i.e., 5%.
            temperature (int | float, optional): Temperature in Kelvin. Default is 1500 K.
            pressure (int | float, optional): Pressure in Pascals. Default is 101325 Pa.
            nb_workers (int | None, optional): Number of worker processes used to parallelize `fit()`
                across compositions. Default is None, which uses all available cores.

        Raises:
            ValueError: If multiple phases are found in the database and phase is not specified.
        """
        from pycalphad import Database

        self.dbf = db if isinstance(db, Database) else Database(db)

        if phase is None and len(self.dbf.phases.keys()) > 1:
            raise ValueError(f"Multiple phases found in the database. Please specify one of {list(self.dbf.phases.keys())}.")

        self.elements = sorted(self.dbf.elements) if elements is None else elements
        self.phase = list(self.dbf.phases.keys())[0] if phase is None else phase
        self.compositions = self._generate_compositions(self.elements, step=step)
        self.temperature = temperature
        self.pressure = pressure
        self.nb_workers = nb_workers if nb_workers is not None else os.cpu_count()

    def fit(self):
        """Fit the stability map by calculating the Hessian eigenvalues for each composition and determining its stability section."""
        with ProcessPoolExecutor(max_workers=self.nb_workers) as executor:
            results = list(executor.map(self._process_row, (row for _, row in self.compositions.iterrows())))

        eigenvalues = pd.DataFrame(results, index=self.compositions.index)
        eigenvalues.columns = [f"eigenvalue_{i + 1}" for i in range(eigenvalues.shape[1])]
        self.compositions = pd.concat([self.compositions, eigenvalues], axis=1)
        self.compositions.dropna(inplace=True)
        self.compositions["negative_eigenvalues"] = self.compositions.apply(self._determine_section, axis=1)

    @staticmethod
    def _generate_compositions(elements: list, step: float = 0.05):
        """Generate all possible compositions where the sum of elements equals 1.

        Uses a given step size, excluding rows where any element is 1.

        Args:
            elements (list): List of element names.
            step (float): Step size for compositions.

        Returns:
            pd.DataFrame: DataFrame containing all valid compositions.
        """
        possible_values = np.arange(0, 1.05, step)

        valid_compositions = [
            composition
            for composition in itertools.product(possible_values, repeat=len(elements))
            if np.isclose(sum(composition), 1.0) and not any(val == 1.0 for val in composition)
        ]

        return pd.DataFrame(valid_compositions, columns=elements)  # ty: ignore[invalid-argument-type]

    @staticmethod
    def _determine_section(row: pd.Series) -> int:
        """Determine the number of negative eigenvalues.

        Args:
            row (pd.Series): A row of eigenvalues.

        Returns:
            int: Number of negative eigenvalues.
        """
        negative_eigenvalues = sum(1 for col in row.index if col.startswith("eigenvalue") and row[col] < 0)
        return negative_eigenvalues

    def _chemical_hessian(self, df_row: pd.Series) -> np.ndarray:
        """Computes the raw (non-orthogonalized) composition Hessian of the Gibbs energy at a composition.

        Builds ``d(mu_i - mu_n)/dx_j`` from a pycalphad `Workspace` evaluated at `df_row`'s
        composition, `self.temperature`, and `self.pressure`. Shared by `StabilityMap._process_row`
        and `CoherentStabilityMap._process_row`, which both need this same chemical term before
        going on to compute (respectively) plain and coherent-elastic-corrected eigenvalues.

        Args:
            df_row (pd.Series): A row of compositions.

        Returns:
            np.ndarray: The raw Hessian matrix, shape ``(len(self.elements) - 1, len(self.elements) - 1)``.
        """
        from pycalphad import Workspace
        from pycalphad import variables as v
        from pycalphad.property_framework import IsolatedPhase

        wks = Workspace(
            database=self.dbf,
            components=self.elements,
            phases=self.phase,
            conditions={
                **{v.X(element): df_row[element] for element in self.elements[:-1]},
                v.T: self.temperature,
                v.P: self.pressure,
            },
        )

        dmu_dx = {
            comp: [
                wks.get(IsolatedPhase(self.phase, wks=wks)(f"MU({comp}).X({indep})"))  # ty: ignore[invalid-argument-type]
                for indep in self.elements[:-1]
            ]
            for comp in self.elements
        }

        return np.array(
            [[dmu_dx[comp][i] - dmu_dx[self.elements[-1]][i] for comp in self.elements[:-1]] for i in range(len(self.elements) - 1)]
        )

    def _orthogonalized_eigenvalues(self, hessian: np.ndarray) -> np.ndarray:
        """Projects a composition Hessian onto an orthonormal simplex basis and sorts its eigenvalues.

        Args:
            hessian (np.ndarray): A composition Hessian, shape ``(len(self.elements) - 1, len(self.elements) - 1)``.

        Returns:
            np.ndarray: Sorted eigenvalues of ``Q.T @ hessian @ Q``, where ``Q`` is the leading
            block of `ORTHOGONALIZATION` sized for `self.elements`.
        """
        orthogonalization_matrix = self.ORTHOGONALIZATION[: len(self.elements) - 1, : len(self.elements) - 1]
        return np.sort(np.linalg.eig(orthogonalization_matrix.T @ hessian @ orthogonalization_matrix)[0])

    @requires("pycalphad", extra="calphad")
    def _process_row(self, df_row: pd.Series) -> list:
        """Process a row of compositions and calculate eigenvalues.

        Args:
            df_row (pd.Series): A row of compositions.

        Returns:
            list: List of eigenvalues.

        Raises:
            ValueError: If the calculation fails.
        """
        try:
            return self._orthogonalized_eigenvalues(self._chemical_hessian(df_row)).tolist()
        except (ValueError, ZeroDivisionError):
            return [None] * (len(self.elements) - 1)

    @requires("matplotlib", extra="plots")
    def plot(self, show: bool = True, save: bool = False, column: str = "negative_eigenvalues", discrete: bool = False) -> tuple:
        """Plot the stability map.

        Args:
            show (bool): Whether to display the plot. Default is True.
            save (bool): Whether to save the plot to current directory. Default is False.
            column (str): Name of the negative-eigenvalue-count column to color points by. Default
                is "negative_eigenvalues".
            discrete (bool): If True, color points by discrete stability category (one color per
                negative-eigenvalue count, sampled from the "RdBu_r" colormap) instead of the
                default continuous "viridis" colorbar. Default is False.

        Returns:
            tuple: Figure and axis objects.

        Raises:
            ValueError: If the number of elements is not 4.
            KeyError: If `column` is missing.
        """
        import matplotlib.pyplot as plt
        from matplotlib.ticker import MaxNLocator

        required_elements = 4
        if len(self.elements) != required_elements:
            raise ValueError("The number of elements must be exactly 4 for plotting.")

        if column not in self.compositions.columns:
            raise KeyError(f"The '{column}' column is missing. Please run the fit() method first.")

        def _generate_regular_pentagon(radius: float = 0.5, center: tuple = (0, 0), rotation_angle: float = 0) -> np.ndarray:
            """Generate vertices of a regular pentagon and rotate it by a given angle.

            Args:
                radius (float): The radius of the circumscribed circle.
                center (tuple): The center of the pentagon.
                rotation_angle (float): Rotation angle in radians.

            Returns:
                np.ndarray: Vertices of the pentagon.
            """
            n = 4
            angles = np.linspace(np.pi / 5, 2 * np.pi + np.pi / 5, n, endpoint=False)

            angles += rotation_angle

            vertices = np.array(
                [
                    [
                        center[0] + radius * np.cos(angle),
                        center[1] + radius * np.sin(angle),
                    ]
                    for angle in angles
                ]
            )
            return vertices

        comps2 = np.dot(
            self.compositions[self.elements],
            _generate_regular_pentagon(radius=1, center=(0, 0), rotation_angle=np.pi / 0.952),
        )

        self.compositions["proj0"], self.compositions["proj1"] = (
            comps2[:, 0],
            comps2[:, 1],
        )

        fig, ax = plt.subplots()

        if discrete:
            n_categories = len(self.elements)
            colors = plt.get_cmap("RdBu_r")(np.linspace(0.05, 0.95, n_categories))
            for count in range(n_categories):
                subset = self.compositions[self.compositions[column] == count]
                ax.scatter(
                    subset["proj0"],
                    subset["proj1"],
                    color=colors[count],
                    alpha=0.7,
                    label=f"{count} negative eigenvalue{'s' if count != 1 else ''}",
                )
            ax.legend(loc="upper right", bbox_to_anchor=(1.35, 1.0), frameon=False)
        else:
            scatter = ax.scatter(
                self.compositions["proj0"],
                self.compositions["proj1"],
                c=self.compositions[column],
                cmap="viridis",
                alpha=0.7,
                vmin=0,
                vmax=len(self.elements) - 1,
            )
            cbar = plt.colorbar(scatter, label="Number of Negative Eigenvalues")
            cbar.ax.yaxis.set_major_locator(MaxNLocator(integer=True))

        ax.set_title(f"T = {self.temperature} K")
        ax.axis("off")

        positions = [(0, 0), (1, 0), (1, 1), (0, 1)]
        alignments = [
            ("center", "center"),
            ("right", "center"),
            ("center", "center"),
            ("left", "center"),
        ]

        for (x, y), (ha, va), element in zip(positions, alignments, self.elements, strict=False):
            ax.text(
                x,
                y,
                element.title(),
                fontsize="large",
                ha=ha,
                va=va,
                transform=ax.transAxes,
            )

        if save:
            system_name = "_".join(self.elements)
            fig.savefig(f"{system_name}-stability_map-{self.temperature}K.png", dpi=300)

        if show:
            fig.show()

        return fig, ax


class CoherentStabilityMap(StabilityMap):
    """Extends `StabilityMap` with a coherent-elastic correction to the Gibbs energy Hessian.

    At each composition grid point, generates an SQS structure, relaxes it and computes its
    elastic constants with a `BaseCalculator`, and adds a coherent-elastic Hessian term (Cahn-type,
    built from the lattice-parameter/composition gradient and the nonisotropic biaxial modulus) to
    the chemical Hessian computed the same way `StabilityMap` does.

    Per-composition-point cost is much higher than plain `StabilityMap` (an SQS optimization plus
    a relaxation per independent composition direction, plus one elastic-constants calculation),
    so `fit()` processes rows sequentially rather than in parallel: MLIP calculators often hold
    GPU/PyTorch state that does not pickle cleanly across worker processes, and GPU-bound work
    generally does not parallelize well across processes anyway.
    """

    @requires("pycalphad", extra="calphad")
    @requires("sqsgenerator", extra="sqsgen")
    def __init__(
        self,
        db: Database | str,
        elements: list[str] | None = None,
        phase: str | None = None,
        crystal_structure: str = "bcc",
        step: float = 0.1,
        temperature: int | float = 1500,
        pressure: int | float = 101325,
        nb_workers: int | None = None,
        calculator: BaseCalculator | None = None,
        sqs_generator: SqsGenerator | None = None,
        supercell_size: tuple[int, int, int] = (5, 5, 5),
        elastic_constants_analyzer: ElasticConstantsAnalyzer | None = None,
        finite_diff_step: float = 0.02,
        atoms_per_cell: int = 2,
    ) -> None:
        """Initialize the CoherentStabilityMap class.

        Args:
            db (Database | str): pycalphad Database object or path to the thermodynamic database file.
            elements (list[str] | None, optional): List of elements to include in the stability map.
                If not provided, all elements in the database will be used.
            phase (str | None, optional): The phase to include in the stability map.
                If not provided, the phase in the database will be used.
            crystal_structure (str, optional): Crystal structure passed to `SqsGenerator.generate`
                (e.g. "bcc", "fcc", "hcp"), independent of the CALPHAD `phase` string. Defaults to
                "bcc". It is the caller's responsibility to keep this physically consistent with
                `phase` and with `atoms_per_cell`.
            step (float, optional): Step size for generating compositions. Default is 0.1 (10%),
                coarser than `StabilityMap`'s default, since each grid point here is far more
                expensive (SQS generation + relaxation + elastic constants, not just a CALPHAD
                equilibrium solve).
            temperature (int | float, optional): Temperature in Kelvin. Default is 1500 K.
            pressure (int | float, optional): Pressure in Pascals. Default is 101325 Pa.
            nb_workers (int | None, optional): Unused by `CoherentStabilityMap` (row processing is
                sequential, not process-pooled); kept for constructor-signature compatibility with
                `StabilityMap`.
            calculator (BaseCalculator | None, optional): Calculator used to relax SQS structures
                and (via `elastic_constants_analyzer`) compute elastic constants. Defaults to a
                lazily constructed default calculator.
            sqs_generator (SqsGenerator | None, optional): Generator used to build an SQS structure
                for each composition. Defaults to a lazily constructed `SqsGenerator()`.
            supercell_size (tuple[int, int, int], optional): Supercell size passed to
                `SqsGenerator.generate`. Defaults to (5, 5, 5).
            elastic_constants_analyzer (ElasticConstantsAnalyzer | None, optional): Analyzer used to
                compute C11/C12/C44 from the relaxed SQS structure. Defaults to a lazily constructed
                `ElasticConstantsAnalyzer(calculator=self.calculator)`.
            finite_diff_step (float, optional): Mole-fraction perturbation used to estimate the
                lattice-parameter composition gradient (`eta`) via forward finite differences.
                Defaults to 0.02.
            atoms_per_cell (int, optional): Number of atoms in the conventional unit cell implied by
                `crystal_structure` (2 for BCC, 4 for FCC, ...). Defaults to 2 (BCC).

        Raises:
            ValueError: If multiple phases are found in the database and phase is not specified.
        """
        self._calculator = calculator
        self._sqs_generator = sqs_generator
        self._elastic_constants_analyzer = elastic_constants_analyzer
        self.crystal_structure = crystal_structure
        self.supercell_size = supercell_size
        self.finite_diff_step = finite_diff_step
        self.atoms_per_cell = atoms_per_cell

        super().__init__(
            db=db,
            elements=elements,
            phase=phase,
            step=step,
            temperature=temperature,
            pressure=pressure,
            nb_workers=nb_workers,
        )

    @lazy_property("_calculator")
    def calculator(self) -> BaseCalculator:
        """Returns the calculator used to relax SQS structures and compute elastic constants.

        Returns:
            BaseCalculator: The calculator object, lazily defaulted if not supplied.
        """
        return default_calculator()

    @lazy_property("_sqs_generator")
    def sqs_generator(self) -> SqsGenerator:
        """Returns the generator used to build an SQS structure for each composition.

        Returns:
            SqsGenerator: The SQS generator object, lazily defaulted if not supplied.
        """
        return SqsGenerator()

    @lazy_property("_elastic_constants_analyzer")
    def elastic_constants_analyzer(self) -> ElasticConstantsAnalyzer:
        """Returns the analyzer used to compute elastic constants from a relaxed structure.

        Returns:
            ElasticConstantsAnalyzer: The analyzer object, lazily defaulted if not supplied.
        """
        return ElasticConstantsAnalyzer(calculator=self.calculator)

    def fit(self):
        """Fit the coherent stability map.

        For each composition, computes both the chemical-only and the chemical+coherent Hessian
        eigenvalues, and the corresponding negative-eigenvalue counts. Row processing is sequential
        (see class docstring for why), not process-pooled like `StabilityMap.fit()`.
        """
        results = self.compositions.apply(self._process_row, axis=1)

        n = len(self.elements) - 1
        columns = [f"chem_eigenvalue_{i + 1}" for i in range(n)] + [f"coherent_eigenvalue_{i + 1}" for i in range(n)]
        eigenvalues = pd.DataFrame(results.tolist(), index=self.compositions.index, columns=columns)  # ty: ignore[invalid-argument-type]

        self.compositions = pd.concat([self.compositions, eigenvalues], axis=1)
        self.compositions.dropna(inplace=True)
        self.compositions["negative_eigenvalues_chem"] = self.compositions.apply(
            lambda row: self._count_negative(row, "chem_eigenvalue"), axis=1
        )
        self.compositions["negative_eigenvalues_coherent"] = self.compositions.apply(
            lambda row: self._count_negative(row, "coherent_eigenvalue"), axis=1
        )

    @staticmethod
    def _count_negative(row: pd.Series, prefix: str) -> int:
        """Counts how many columns starting with `prefix` hold a negative value.

        Args:
            row (pd.Series): A row of eigenvalues.
            prefix (str): Column-name prefix to filter on (e.g. "chem_eigenvalue").

        Returns:
            int: Number of matching columns with a negative value.
        """
        return sum(1 for col in row.index if col.startswith(prefix) and row[col] < 0)

    def _relax_composition(self, fractions: dict[str, float]) -> tuple[float, Structure]:
        """Generates an SQS structure at `fractions`, relaxes it, and measures its lattice parameter.

        Args:
            fractions (dict[str, float]): Mole fraction for each element in `self.elements`.

        Returns:
            tuple[float, Structure]: The effective (volume-averaged) cubic lattice parameter in
            Angstrom, and the relaxed structure.
        """
        composition = Composition({element.capitalize(): fraction for element, fraction in fractions.items()})
        sqs = self.sqs_generator.generate(
            composition,
            crystal_structure=self.crystal_structure,
            supercell_size=self.supercell_size,
        )
        relaxed = self.calculator.relax(sqs["structure"])["final_structure"]
        lattice_parameter = (relaxed.volume / (len(relaxed) / self.atoms_per_cell)) ** (1 / 3)
        return lattice_parameter, relaxed

    def _composition_gradient(self, fractions: dict[str, float], lattice_parameter: float) -> np.ndarray:
        """Estimates the lattice-parameter composition gradient `eta` via forward finite differences.

        Args:
            fractions (dict[str, float]): Mole fraction for each element in `self.elements`.
            lattice_parameter (float): Lattice parameter (Angstrom) at `fractions`, from `_relax_composition`.

        Returns:
            np.ndarray: Coherency-strain row vector (shape (1, n-1)), one entry per independent
            composition direction, `d(ln a)/dx_i`.
        """
        dependent = self.elements[-1]
        gradients = []
        for element in self.elements[:-1]:
            perturbed = dict(fractions)
            perturbed[element] += self.finite_diff_step
            perturbed[dependent] -= self.finite_diff_step
            perturbed_lattice_parameter, _ = self._relax_composition(perturbed)
            gradients.append((perturbed_lattice_parameter - lattice_parameter) / self.finite_diff_step / lattice_parameter)
        return np.array([gradients])

    @staticmethod
    def _zener_modulus(c11: float, c12: float, c44: float) -> float:
        """Computes the nonisotropic (Zener) biaxial modulus for a cubic phase.

        The sign of the elastic anisotropy factor (``2*C44 - C11 + C12``) selects between the two
        closed-form biaxial-modulus expressions; both are algebraically equal at the ``== 0``
        boundary, so it is handled by the first branch instead of being left unhandled.

        Args:
            c11 (float): Elastic constant C11 (Pa).
            c12 (float): Elastic constant C12 (Pa).
            c44 (float): Elastic constant C44 (Pa).

        Returns:
            float: The biaxial modulus Y (Pa).
        """
        anisotropy = 2 * c44 - c11 + c12
        if anisotropy >= 0:
            return (c11 + 2 * c12) * (c11 - c12) / c11
        return 6 * (c11 + 2 * c12) * c44 / (4 * c44 + c11 + 2 * c12)

    @staticmethod
    def _coherent_hessian(eta: np.ndarray, y: float, molar_volume: float) -> np.ndarray:
        """Computes the coherent-elastic contribution to the Gibbs energy Hessian.

        Args:
            eta (np.ndarray): Coherency-strain row vector (shape ``(1, n-1)``), one entry per
                independent composition variable.
            y (float): Biaxial modulus (Pa), e.g. from `_zener_modulus`.
            molar_volume (float): Molar volume (m^3/mol), e.g. from `_molar_volume_from_lattice_parameter`.

        Returns:
            np.ndarray: The coherent elastic Hessian matrix, ``2 * y * molar_volume * (eta (x) eta)``.
        """
        return 2 * y * molar_volume * (eta.reshape(-1, 1) @ eta.reshape(1, -1))

    @staticmethod
    def _molar_volume_from_lattice_parameter(lattice_parameter_angstrom: float, atoms_per_cell: int = 2) -> float:
        """Computes the molar volume of a conventional cubic unit cell.

        Args:
            lattice_parameter_angstrom (float): Cubic lattice parameter, in Angstrom.
            atoms_per_cell (int, optional): Number of atoms in the conventional unit cell
                (e.g. 2 for BCC, 4 for FCC). Defaults to 2.

        Returns:
            float: Molar volume V = a^3 * N_A / atoms_per_cell, in m^3/mol.
        """
        return (lattice_parameter_angstrom * 1e-10) ** 3 * Avogadro / atoms_per_cell

    def _process_row(self, df_row: pd.Series) -> list:
        """Processes a row of compositions, computing both chemical and chemical+coherent eigenvalues.

        Args:
            df_row (pd.Series): A row of compositions.

        Returns:
            list: Chemical eigenvalues followed by chemical+coherent eigenvalues (each length
            `len(self.elements) - 1`).
        """
        try:
            chem_hessian = self._chemical_hessian(df_row)

            fractions = {element: df_row[element] for element in self.elements}
            lattice_parameter, relaxed = self._relax_composition(fractions)
            elastic_properties = self.elastic_constants_analyzer.calculate(relaxed, is_relaxed=True)
            eta = self._composition_gradient(fractions, lattice_parameter)
            biaxial_modulus = self._zener_modulus(
                elastic_properties["C_11"] * 1e9,
                elastic_properties["C_12"] * 1e9,
                elastic_properties["C_44"] * 1e9,
            )
            molar_volume = self._molar_volume_from_lattice_parameter(lattice_parameter, self.atoms_per_cell)
            coherent_hessian_matrix = chem_hessian + self._coherent_hessian(eta, biaxial_modulus, molar_volume)

            chem_eigenvalues = self._orthogonalized_eigenvalues(chem_hessian)
            coherent_eigenvalues = self._orthogonalized_eigenvalues(coherent_hessian_matrix)

            return chem_eigenvalues.tolist() + coherent_eigenvalues.tolist()

        except Exception:  # noqa: BLE001
            return [None] * 2 * (len(self.elements) - 1)
