name: materialsframework
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - sqsgenerator
  - phonopy
  - phono3py
  - pip:
      - matgl
      - chgnet
      - mace-torch
      - openpyxl
      - sevenn
      - orb-models
      - git+https://github.com/dwastberg/pynanoflann
