name: materialsframework
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - sqsgenerator
  - phonopy
  - phono3py
  - pyg::pytorch-scatter
  - pyg::pytorch-sparse
  - pyg::pytorch-cluster
  - pip:
      - openpyxl
      - matgl
      - chgnet
      - mace-torch
      - sevenn
      - orb-models
      - git+https://github.com/dwastberg/pynanoflann
      - git+https://github.com/FAIR-Chem/fairchem.git@omat24#egg=fairchem-core&subdirectory=packages/fairchem-core