name: materialsframework-matgl
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - sqsgenerator
  - phonopy
  - phono3py
  - elastic
  - pandas
  - cpuonly
  - pytorch=2.4.1
  - torchvision
  - numpy<2
  - ase
  - pymatgen
  - scipy
  - pip
  - pip:
      - openpyxl
      - pycalphad
      - pandarallel
      - --find-links https://data.dgl.ai/wheels/torch-2.4/repo.html
      - dgl==2.4.0
      - --find-links https://data.pyg.org/whl/torch-2.4.0+cpu.html
      - torch_scatter==2.1.2+pt24cpu
      - torch_geometric==2.5.3
      - lightning<=2.5.1
      - matgl