name: materialsframework
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - sqsgenerator
  - phonopy
  - phono3py
  - pandas
  - elastic
  - pip:
      - openpyxl
      - pandarallel
      - ase
      - pymatgen
      - matgl
      - orb-models
      - git+https://github.com/cjkunselman18/pycalphad.git