name: materialsframework
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - sqsgenerator
  - phonopy
  - phono3py
  - pip:
      - matgl
      - pymatgen
      - chgnet
      - mace-torch
      - openpyxl