name: materialsframework-mace
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - sqsgenerator
  - phonopy
  - phono3py
  - elastic
  - pandas
  - cpuonly
  - pytorch=2.4.1
  - numpy<2
  - ase
  - pymatgen
  - scipy
  - icet
  - pip
  - pip:
      - openpyxl
      - git+https://github.com/cjkunselman18/pycalphad.git
      - pandarallel
      - e3nn==0.4.4                     # hard pin in MACE
      - mace-torch
