name: materialsframework-main
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - sqsgenerator
  - phonopy
  - phono3py
  - elastic
  - cpuonly
  - pytorch=2.4.1
  - torchvision
  - tensorflow=2.17.*
  - numpy<2
  - cython
  - ase
  - pymatgen
  - pandas
  - deepmd-kit
  - pip
  - pip:
      - openpyxl
      - pandarallel
      - --find-links https://data.dgl.ai/wheels/torch-2.4/repo.html
      - dgl==2.4.0
      - --find-links https://data.pyg.org/whl/torch-2.4.0+cpu.html
      - torch_scatter==2.1.2+pt24cpu
      - torch_geometric==2.5.3
      - e3nn>=0.5
      - lightning<=2.5.1
      - chgnet
      - matgl
      - mattersim
      - sevenn
      - git+https://github.com/facebookresearch/fairchem.git#subdirectory=packages/fairchem-core
      - git+https://github.com/atomly-materials-research-lab/GPTFF.git
      - tensorpotential==0.5.1