"""This module provides a class to perform a hydrogen solubility analysis on BCC host structures.

The `HSolubilityAnalyzer` class computes octahedral and tetrahedral hydrogen insertion
energies using structures generated by `HSolubilityTransformation` and reports the preferred
site type and solution energy relative to a hydrogen reference.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from materialsframework.analysis.base import BaseAnalyzer
from materialsframework.analysis.utils import require_properties
from materialsframework.transformations.h_solubility import HSolubilityTransformation
from materialsframework.utils import lazy_property

if TYPE_CHECKING:
    from ase import Atoms
    from pymatgen.core import Composition, Structure

    from materialsframework.tools.calculator import BaseCalculator

__author__ = "Doguhan Sariturk"
__email__ = "dogu.sariturk@gmail.com"


class HSolubilityAnalyzer(BaseAnalyzer):
    """A class to evaluate H insertion energetics in BCC octahedral/tetrahedral sites."""

    def __init__(
        self,
        calculator: BaseCalculator | None = None,
        h_solubility_transformation: HSolubilityTransformation | None = None,
        hydrogen_reference_energy: float = 0.0,
    ) -> None:
        """Initializes the analyzer.

        Args:
            calculator (BaseCalculator | None, optional): Calculator for total-energy evaluations.
            h_solubility_transformation (HSolubilityTransformation | None, optional): Optional transformation instance.
            hydrogen_reference_energy (float, optional): Reference energy per inserted hydrogen atom,
                e.g., 1/2 E(H2).
        """
        super().__init__(calculator)
        self._h_solubility_transformation = h_solubility_transformation
        self.hydrogen_reference_energy = float(hydrogen_reference_energy)

    @require_properties("energy")
    def calculate(
        self,
        structure: Atoms | Structure | None = None,
        composition: Composition | str | None = None,
        supercell_size: tuple[int, int, int] = (1, 1, 1),
        site_types: tuple[str, ...] = ("octahedral", "tetrahedral"),
        max_sites_per_type: int | None = 1,
        is_relaxed: bool = False,
    ) -> dict[str, Any]:
        """Calculates H insertion energies and the minimum solution energy.

        Args:
            structure (Atoms | Structure | None): Host structure to evaluate.
            composition (Composition | str | None): Composition for optional SQS host generation.
            supercell_size (tuple[int, int, int], optional): Supercell used for host generation.
            site_types (tuple[str, ...], optional): Interstitial site families to evaluate.
            max_sites_per_type (int | None, optional): Candidate count per site family.
            is_relaxed (bool, optional): If ``True``, use single-point energies only.

        Returns:
            dict[str, Any]: Dictionary with keys:
                - ``host_energy``: Relaxed host energy (eV).
                - ``hydrogen_reference_energy``: Reference hydrogen energy (eV).
                - ``octahedral_insertion_energies``: Insertion energies for octahedral sites (eV).
                - ``tetrahedral_insertion_energies``: Insertion energies for tetrahedral sites (eV).
                - ``min_octahedral_insertion_energy``: Minimum octahedral insertion energy (eV).
                - ``min_tetrahedral_insertion_energy``: Minimum tetrahedral insertion energy (eV).
                - ``preferred_site_type``: Site family with minimum insertion energy.
                - ``solution_energy``: Minimum solution energy relative to H reference (eV).

        Raises:
            ValueError: If required calculator capabilities are missing or no insertion energies are produced.
        """
        initial_result = self.h_solubility_transformation.apply_transformation(
            structure=structure,
            composition=composition,
            supercell_size=supercell_size,
            site_types=site_types,
            max_sites_per_type=max_sites_per_type,
        )

        host_structure = initial_result["host_structure"]
        insertion_structures = initial_result["structures"]

        if is_relaxed:
            host_energy = float(self.calculator.calculate(host_structure)["energy"])
        else:
            relaxed_host = self.calculator.relax(host_structure)
            host_structure = relaxed_host["final_structure"]
            host_energy = float(relaxed_host["energy"])

            relaxed_result = self.h_solubility_transformation.apply_transformation(
                structure=host_structure,
                site_types=site_types,
                max_sites_per_type=max_sites_per_type,
            )
            insertion_structures = relaxed_result["structures"]

        octahedral_energies = self._calculate_site_energies(
            host_energy,
            insertion_structures.get("octahedral", []),
            is_relaxed,
        )
        tetrahedral_energies = self._calculate_site_energies(
            host_energy,
            insertion_structures.get("tetrahedral", []),
            is_relaxed,
        )

        min_octahedral = min(octahedral_energies) if octahedral_energies else None
        min_tetrahedral = min(tetrahedral_energies) if tetrahedral_energies else None

        if min_octahedral is None and min_tetrahedral is None:
            raise ValueError("No insertion energies were generated for the requested site types.")

        if min_tetrahedral is None or (min_octahedral is not None and min_octahedral <= min_tetrahedral):
            preferred_site = "octahedral"
            solution_energy = min_octahedral
        else:
            preferred_site = "tetrahedral"
            solution_energy = min_tetrahedral

        return {
            "host_energy": host_energy,
            "hydrogen_reference_energy": self.hydrogen_reference_energy,
            "octahedral_insertion_energies": octahedral_energies,
            "tetrahedral_insertion_energies": tetrahedral_energies,
            "min_octahedral_insertion_energy": min_octahedral,
            "min_tetrahedral_insertion_energy": min_tetrahedral,
            "preferred_site_type": preferred_site,
            "solution_energy": solution_energy,
        }

    def _calculate_site_energies(
        self,
        host_energy: float,
        defect_structures: list[Structure],
        is_relaxed: bool,
    ) -> list[float]:
        """Calculate insertion energies for provided defect structures.

        Args:
            host_energy: Host reference energy.
            defect_structures: Structures containing one inserted hydrogen atom.
            is_relaxed: Whether to perform single-point (`True`) or relaxation (`False`).

        Returns:
            Insertion energies for each defect structure.
        """
        energies: list[float] = []
        for defect_structure in defect_structures:
            if is_relaxed:
                defect_energy = float(self.calculator.calculate(defect_structure)["energy"])
            else:
                defect_energy = float(self.calculator.relax(defect_structure)["energy"])

            energies.append(defect_energy - host_energy - self.hydrogen_reference_energy)

        return energies

    @lazy_property("_h_solubility_transformation")
    def h_solubility_transformation(self) -> HSolubilityTransformation:
        """Return transformation used for interstitial-structure generation.

        Returns:
            H-solubility transformation instance.
        """
        return HSolubilityTransformation()
