"""This module contains the `EOSTransformation` class that generates deformed structures for Equation of State (EOS) calculations.

The `EOSTransformation` class creates a series of deformed structures by applying uniform volumetric strains to an undeformed structure.
These deformed structures can be used to calculate the equation of state, which describes the relationship between energy and volume for a material.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
from pymatgen.transformations.standard_transformations import DeformStructureTransformation

if TYPE_CHECKING:
    from pymatgen.core import Structure

__author__ = "Doguhan Sariturk"
__email__ = "dogu.sariturk@gmail.com"


class EOSTransformation:
    """A class used to generate deformed structures for EOS (Equation of State) calculations.

    The `EOSTransformation` class generates a series of deformed structures by applying
    uniform volumetric strains to an undeformed structure. These deformed structures can
    be used to calculate the equation of state.
    """

    def __init__(
        self,
        start: float = -0.1,
        stop: float = 0.1,
        num: int = 11,
    ) -> None:
        """Initializes the `EOSTransformation` object.

        Args:
            start (float, optional): The starting strain value to apply to the structure. Defaults to -0.1.
            stop (float, optional): The stopping strain value to apply to the structure. Defaults to 0.1.
            num (int, optional): The number of strain values to generate between the start and stop. Defaults to 11.

        Note:
            The `start` and `stop` parameters define the range of strains to apply, while `num` determines how many
            evenly spaced strain values will be generated within that range. The resulting deformed structures
            will be stored in the `structures` attribute.
        """
        self._strains = np.linspace(start, stop, num)

        self.structures: list[Structure] = []

    def apply_transformation(self, structure: Structure) -> None:
        """Applies the transformation to generate deformed structures for EOS calculations.

        This method creates a series of deformed structures by applying uniform volumetric strains to the input structure.
        Each deformed structure is generated by scaling the lattice vectors of the input structure according to the specified strain values.
        The resulting deformed structures are stored in the `structures` attribute.

        Args:
            structure (Structure): The initial, undeformed structure to be used for EOS calculations.
        """
        for strain in self._strains:
            dst = DeformStructureTransformation((np.identity(3) * (1.0 + strain)).tolist())
            self.structures.append(dst.apply_transformation(structure))
